vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /images/article_image
            upload_destination: '%kernel.project_dir%/public/images/article_image'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer