<?php

namespace ContainerQxxuxia;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NjuvZH0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.njuvZH0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.njuvZH0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\TestControlerController::delete' => ['privates', '.service_locator.ZkRn5be', 'get_ServiceLocator_ZkRn5beService', true],
            'App\\Controller\\TestControlerController::edit' => ['privates', '.service_locator.ZkRn5be', 'get_ServiceLocator_ZkRn5beService', true],
            'App\\Controller\\TestControlerController::index' => ['privates', '.service_locator.55Rpv1s', 'get_ServiceLocator_55Rpv1sService', true],
            'App\\Controller\\TestControlerController::jsp' => ['privates', '.service_locator.55Rpv1s', 'get_ServiceLocator_55Rpv1sService', true],
            'App\\Controller\\TestControlerController::show' => ['privates', '.service_locator.ZkRn5be', 'get_ServiceLocator_ZkRn5beService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\TestControlerController:delete' => ['privates', '.service_locator.ZkRn5be', 'get_ServiceLocator_ZkRn5beService', true],
            'App\\Controller\\TestControlerController:edit' => ['privates', '.service_locator.ZkRn5be', 'get_ServiceLocator_ZkRn5beService', true],
            'App\\Controller\\TestControlerController:index' => ['privates', '.service_locator.55Rpv1s', 'get_ServiceLocator_55Rpv1sService', true],
            'App\\Controller\\TestControlerController:jsp' => ['privates', '.service_locator.55Rpv1s', 'get_ServiceLocator_55Rpv1sService', true],
            'App\\Controller\\TestControlerController:show' => ['privates', '.service_locator.ZkRn5be', 'get_ServiceLocator_ZkRn5beService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\TestControlerController::delete' => '?',
            'App\\Controller\\TestControlerController::edit' => '?',
            'App\\Controller\\TestControlerController::index' => '?',
            'App\\Controller\\TestControlerController::jsp' => '?',
            'App\\Controller\\TestControlerController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\TestControlerController:delete' => '?',
            'App\\Controller\\TestControlerController:edit' => '?',
            'App\\Controller\\TestControlerController:index' => '?',
            'App\\Controller\\TestControlerController:jsp' => '?',
            'App\\Controller\\TestControlerController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
