<?php

namespace ContainerO7suHkm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_55Rpv1sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.55Rpv1s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.55Rpv1s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'testRepository' => ['privates', 'App\\Repository\\TestRepository', 'getTestRepositoryService', true],
        ], [
            'testRepository' => 'App\\Repository\\TestRepository',
        ]);
    }
}
