<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBXbpZdH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBXbpZdH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBXbpZdH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBXbpZdH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBXbpZdH\App_KernelDevDebugContainer([
    'container.build_hash' => 'BXbpZdH',
    'container.build_id' => 'cff629dc',
    'container.build_time' => 1634904831,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBXbpZdH');
