<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO7suHkm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO7suHkm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO7suHkm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO7suHkm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO7suHkm\App_KernelDevDebugContainer([
    'container.build_hash' => 'O7suHkm',
    'container.build_id' => 'cfb804cb',
    'container.build_time' => 1633699638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO7suHkm');
