<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIBcKCgc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIBcKCgc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIBcKCgc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIBcKCgc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIBcKCgc\App_KernelDevDebugContainer([
    'container.build_hash' => 'IBcKCgc',
    'container.build_id' => '34a0585f',
    'container.build_time' => 1633440325,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIBcKCgc');
